src/Entity/Ruta.php
<?php

namespace App\Entity;

use App\Repository\RutaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: RutaRepository::class)]
#[Broadcast]
class Ruta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $descripcion = null;

    #[ORM\Column(length: 255)]
    private ?string $foto = null;

    #[ORM\Column(length: 255)]
    private ?string $punto_inicio = null;

    #[ORM\Column]
    private ?int $participantes = null;

    #[ORM\OneToMany(mappedBy: 'cod_ruta', targetEntity: Tour::class, cascade: ['persist', 'remove'])]
    private Collection $tours;

    #[ORM\Column(type: "json")]
    private ?array $programacion = null;

    #[ORM\OneToMany(mappedBy: 'cod_ruta', targetEntity: RutaVisita::class, cascade: ['persist', 'remove'])]
    private Collection $rutaVisitas;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_inicio = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_fin = null;

    public function __construct()
    {
        $this->tours = new ArrayCollection();
        $this->rutaVisitas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(string $foto): static
    {
        $this->foto = $foto;

        return $this;
    }

    public function getPuntoInicio(): ?string
    {
        return $this->punto_inicio;
    }

    public function setPuntoInicio(string $punto_inicio): static
    {
        $this->punto_inicio = $punto_inicio;

        return $this;
    }

    public function getParticipantes(): ?int
    {
        return $this->participantes;
    }

    public function setParticipantes(int $participantes): static
    {
        $this->participantes = $participantes;

        return $this;
    }

    /**
     * @return Collection<int, Tour>
     */
    public function getTours(): Collection
    {
        return $this->tours;
    }

    public function addTour(Tour $tour): static
    {
        if (!$this->tours->contains($tour)) {
            $this->tours->add($tour);
            $tour->setCodRuta($this);
        }

        return $this;
    }

    public function removeTour(Tour $tour): static
    {
        if ($this->tours->removeElement($tour)) {
            // set the owning side to null (unless already changed)
            if ($tour->getCodRuta() === $this) {
                $tour->setCodRuta(null);
            }
        }

        return $this;
    }

    public function getProgramacion(): ?array
    {
        return $this->programacion;
    }
    
    public function setProgramacion(array $programacion): static
    {
        $this->programacion = $programacion;
    
        return $this;
    }

    /**
     * @return Collection<int, RutaVisita>
     */
    public function getRutaVisitas(): Collection
    {
        return $this->rutaVisitas;
    }

    public function addRutaVisita(RutaVisita $rutaVisita): static
    {
        if (!$this->rutaVisitas->contains($rutaVisita)) {
            $this->rutaVisitas->add($rutaVisita);
            $rutaVisita->setCodRuta($this);
        }

        return $this;
    }

    public function removeRutaVisita(RutaVisita $rutaVisita): static
    {
        if ($this->rutaVisitas->removeElement($rutaVisita)) {
            // set the owning side to null (unless already changed)
            if ($rutaVisita->getCodRuta() === $this) {
                $rutaVisita->setCodRuta(null);
            }
        }

        return $this;
    }

    public function getFechaInicio(): ?\DateTimeInterface
    {
        return $this->fecha_inicio;
    }

    public function setFechaInicio(\DateTimeInterface $fecha_inicio): static
    {
        $this->fecha_inicio = $fecha_inicio;

        return $this;
    }

    public function getFechaFin(): ?\DateTimeInterface
    {
        return $this->fecha_fin;
    }

    public function setFechaFin(\DateTimeInterface $fecha_fin): static
    {
        $this->fecha_fin = $fecha_fin;

        return $this;
    }

    // En tu entidad Ruta
public function __toString(): string
{
    // Suponiendo que 'nombre' es la propiedad que quieres mostrar
    return $this->nombre;
}

// public function serializeToJson(): string
// {
//     $data = [
//         'id' => $this->id,
//         'nombre' => $this->nombre,
//         'descripcion' => $this->descripcion,
//         'foto' => $this->foto,
//         'punto_inicio' => $this->punto_inicio,
//         'participantes' => $this->participantes,
//         'programacion' => $this->programacion,
//         'fecha_inicio' => $this->fecha_inicio,
//         'fecha_fin' => $this->fecha_fin,
//         // ... (other properties)
//     ];

//     return json_encode($data);
// }

// // Deserialize the entity
// public function unserialize(string $data): void
// {
//     $values = unserialize($data);
//     $this->id = $values['id'];
//     $this->nombre = $values['nombre'];
//     $this->descripcion = $values['descripcion'];
//     $this->foto = $values['foto'];
//     $this->punto_inicio = $values['punto_inicio'];
//     $this->participantes = $values['participantes'];
//     $this->programacion = $values['programacion'];
//     $this->fecha_inicio = $values['fecha_inicio'];
//     $this->fecha_fin = $values['fecha_fin'];
//     // ... (other properties)
// }


}

src/Controller/CrearRutaController.php
<?php

namespace App\Controller;

use App\Entity\Visita;
use App\Entity\localidad;
use App\Entity\User;
use app\Entity\Ruta;
use App\Repository\UserRepository;
use App\Repository\RutaRepository;
USE App\Repository\VisitaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;  
USE Symfony\Component\HttpFoundation\Request;
use App\Repository\LocalidadRepository;
USE Symfony\Component\Serializer\SerializerInterface;
use App\Controller\Api\DevueltaRoute;
use EasyCorp\Bundle\EasyAdminBundle\Controller\DashboardControllerInterface;

class CrearRutaController extends AbstractController
{
    private DevueltaRoute $devueltaRoute;
    private SerializerInterface $serializer;
    private EntityManagerInterface $entityManager;
    public function __construct(DevueltaRoute $devueltaRoute, SerializerInterface $serializer, EntityManagerInterface $entityManager)
    {
        $this->devueltaRoute = $devueltaRoute;
        $this->serializer = $serializer;
        $this->entityManager = $entityManager;
    }

    
    #[Route('/crear/ruta', name: 'app_crear_ruta')]
    public function index(VisitaRepository $visitaRepository, LocalidadRepository $localidadesRepository, UserRepository $userRepository ): Response
    {
        $localidades = $localidadesRepository->findAllLocalidades();
        $visitas = $visitaRepository->findAllVisitas();
        $guias = $userRepository->findUsersByRole('ROLE_GUIDE');
    
        return $this->render('crear_ruta/index.html.twig', [
            'controller_name' => 'CrearRutaController',
            'localidades' => $localidades,
            'visitas' => $visitas,
            'guias' => $guias
        ]);
    }
    
    



    #[Route('/filtrar-visitas/{localidadId}', name: 'filtrar_visitas')]
    public function filtrarVisitas($localidadId, VisitaRepository $visitaRepository): Response
    {
        $visitas = $visitaRepository->findVisitasByLocalidad($localidadId);
    
        return $this->json(['visitas' => $visitas]);
    }
    
    

    public function seleccionarGuias()
    {
        
        $userRepository = $this->entityManager->getRepository('App\Entity\User');

        
        $guias = $userRepository->findBy(['roles' => ['ROLE_GUIDE']]);

        return $guias;
    }

    #[Route('/editar/ruta', name: 'app_editar_ruta')]
    public function editarRuta(): Response
    {
        // $response = $this->devueltaRoute->uploadCreateRoute(new Request(), $this->entityManager);
        // $rutas = json_decode($response->getContent(), true);
    
        return $this->render('crear_ruta/editar_ruta.html.twig', [
            // 'rutas' => $rutas
        ]);
    }



}

templates/crear_ruta/editar_ruta.html.twig
{% extends ea.templatePath('layout') %}

{# {% extends '@EasyAdmin/page/content.html.twig' %} #}
{% block content_title %}Editar {% endblock %}
{% block title %}Editar{% endblock %}


  
      {% block mystylesheets %}
<link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
<link rel="stylesheet" href="{{ asset('css/jquery-ui.structure.css') }}">
<link rel="stylesheet" href="{{ asset('css/jquery-ui.theme.css') }}">
<link rel="stylesheet" href="{{ asset('css/richtext.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/image-uploader.min.css') }}">
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<link rel="stylesheet" href="{{ asset('css/jquery.datetimepicker.css') }}">

<link rel="stylesheet" href="{{ asset('css/estilo.css') }}">

    
    {% endblock %}


{% block myjavascripts %}
  
<script src="{{ asset('js/jquery-3.7.1.js') }}"></script>
<script src="{{ asset('js/jquery-ui.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('js/jquery.richtext.min.js') }}"></script>
<script src="{{ asset('js/image-uploader.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>    
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://kit.fontawesome.com/91464fdedc.js" crossorigin="anonymous"></script>


{# <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script> #}
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<script src="{{ asset('js/crearRuta.js') }}"></script>
<script src="{{ asset('js/añadirRuta.js') }}"></script>
<script src="{{ asset('js/extraerVisitas.js') }}"></script>
<script src="{{ asset('js/añadirVisita.js') }}"></script>

<script src="{{ asset('js/editarRuta.js') }}"></script>
{# <script src="{{ asset('js/generarTour.js') }}"></script> #}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock %}


{% block main %}
<body>
    {# <div id="modal"> #}
        <div id="main">

{#####_________________________________________PESTAÑA CREAR/RUTA_____________________________######}
                <div id="tabs">
                    <ul>
                    <li><a href="#tabs-1">Ruta."{{ route.Id }}"</a></li>
                    </ul>
                    <div id="tabs-1">
                    <div class="primerLinea">
                      <div>
                     <label for="titulo">Titulo:</label>
                     <input type="hidden" id="rutaId" value="{{ route.Id }}">
                     <input type="text" name="titulo" id="inputTitulo" value="{{ route.nombre }}" required>
                     </div>
                      <div>
                     <label for="fechaRuta">Fecha inicio y fin </label> 
                    <input type="text" id="daterange" name="daterange" value="{{ route.fechaInicio|date('d/m/Y H:i') ~ ' - ' ~ route.fechaFin|date('d/m/Y H:i') }}" required />
                     </div>
                     <div>
                     <label for="aforo" required >Aforo:</label>
                    <input type="number" min="6" max="20" id="aforo" value="{{ route.participantes }}"> 
                      </div>
                        </div>
                         <br>
                      
                        <div class="primerLinea">
             {% set coordenadas = route.getPuntoInicio() %}
{% set coordenadasArray = coordenadas|trim('(')|trim(')')|split(', ') %}

<div>
    <label for="puntoEncuentro" class="subt">Punto de encuentro:</label>
    <button id="btnMapa">Mapa</button>
</div>
<div>
    <label for="x" required>EjeX:</label>
    <input type="number" name="x" id="x" value="{{ coordenadasArray[0]|default('') }}" required>
</div>
<div>
    <label for="y" required>EjeY:</label>
    <input type="number" name="y" id="y" value="{{ coordenadasArray[1]|default('') }}" required>
</div>
</div>
                      <br>
                        <div id="modal"></div>
                 <label for="descripcion" class="subt">Descripción:</label>
<textarea name="descripcion" id="textarea" cols="1" rows="1">{{ route.descripcion }}</textarea>

                     <label for="subirImagen" class="subt">Subir Imagen:</label>
<form action="url" enctype="multipart/form-data" id="foto">
    <div id="input-images" class"input-images">
        {% if route.FOTO is defined %}
            <div class="uploaded-image">
                <img src="{{ path('mostrar_imagen', {'nombreImagen': route.FOTO}) }}" alt="Imagen de la Ruta" width="300px">
                <!-- Puedes agregar un botón de eliminación o edición si lo deseas -->
            </div>
        {% endif %}
    </div>
</form>


                      
                        
                        <br>
                           <button class="btn btn-primary" type="button" id="btnEditar" >EDITAR RUTA</button>
                    </div>
{#####_________________________________________PESTAÑA VISITAS____________________________________________________######}

                {# <div id="tabs-2">
                  <label for="">Selecciona una localidad</label>
                  <select name="" id="salutation" class="salutation">
                    <option disabled selected>Click en una</option>
                    {% for localidad in localidades %}
                      <option value="{{ localidad.id }}">{{ localidad.nombre }}</option>
                    {% endfor %}
                  </select>
                  <br>
                  <div class="titulosVisitas">
                    <label for="">Lugares disponibles</label>
                    <label for="">Lugares elegidos</label>
                  </div>
                  <div id="items" class="items">
                    <ul id="sortable1" class="droptrue">
                      {% for visita in visitas %}
                        <li class="visita" data-localidad="{{ visita.cod_localidad}}" data-visita-id="{{ visita.id }}">
                          <div class="image-container">
                            <img src="{{ asset('public/img/visitas/' ~ visita.foto) }}" alt="{{ visita.nombre }}">
                            <p class="text-center">{{ visita.nombre }}</p>
                          </div>
                        </li>
                      {% endfor %}
                    </ul>
                    <ul id="sortable2" class="droptrue">
                      
                    </ul>
                  </div>
                  <br>
                    <button class="btn btn-primary" type="button" Id="btnCrearVisitasTour">CREAR VISITAS</button>
                </div> #}

{#_____________________________________________PESTAÑA PROGRAMACION__________________________________________________#}
                    {# <div id="tabs-3">
                        <div class="fechaPeriodo">
                        <label for="periodo">Periodo</label> 
                       <input type="text" name="datefilter" value="" />
                          </div>
                          <div id="diasSemana">
                            <div>
                              <input type="checkbox" id="lunes" name="dia" value="L">
                              <label for="lunes">Lunes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="martes" name="dia" value="M">
                              <label for="martes">Martes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="miercoles" name="dia" value="X">
                            <label for="miercoles">Miércoles</label>
                            </div>
                            <div>
                              <input type="checkbox" id="jueves" name="dia" value="J">
                              <label for="jueves">Jueves</label>
                            </div>
                            <div>
                              <input type="checkbox" id="viernes" name="dia" value="V">
                              <label for="viernes">Viernes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="sabado" name="dia" value="S">
                              <label for="sabado">Sábado</label>
                            </div>
                            <div>
                              <input type="checkbox" id="domingo" name="dia" value="D">
                              <label for="domingo">Domingo</label>
                            </div>
                          </div>
                          <div id="otrasOpcion">
                          <div>
                            <label for="salutation">Hora </label>
                            <input type="time" id="time" />
                          </div>           
                          <div>  
                          <form>
                          <label for="selectGuia">Selecciona un guía</label>
                           <select name="selectGuia" id="selectGuia">
                           <option disabled selected>....</option>
                             {% for guia in guias %}
                             <option value="{{guia.id}}" >{{ guia.nombre }}</option>
                             {% endfor %}
                            </select> 
                           </form>
                          </div> 
                         </div>
                        <br>
                        <div class="btnn">
                         <button class="bttnEstilo" id="guardar">Archivar</button>
                        </div>                 
                          <br>
                          <table id="tabla" border="1">
                            <thead>
                              <tr>
                                <th>Rango de fecha</th>
                                <th>Días</th>
                                <th>Hora</th>
                                <th>Guía</th>
                              </tr>
                            </thead>
                            <tbody>
                            </tbody>
                          </table>
                          <br>
                     <button class="btn btn-danger" type="button" id="btnCrearProgramacion">CREAR PROGRAMACION Y GENERAR TOUR</button>
                    </div>
                      
                </div> #}

{##________________________________________BOTONES CONTROLERS_______________________________________________________##}                
                {# <div class="d-grid gap-2"> #}
                
                
                   
                    {# <button class="btn btn-danger" type="button" id="btnTour">GENERAR TOUR</button> #}
                  {# </div>         
        </div>
         #}
{# <div id="errorModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="errorMessage"></p>
    </div>
</div> #}
    {# </div> #}
{# </body> #}
{% endblock %}

templates/crear_ruta/index.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}
{% block content_title %}Crear Ruta {% endblock %}
{% block title %}CrearRuta {% endblock %}


  
      {% block mystylesheets %}
<link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
<link rel="stylesheet" href="{{ asset('css/jquery-ui.structure.css') }}">
<link rel="stylesheet" href="{{ asset('css/jquery-ui.theme.css') }}">
<link rel="stylesheet" href="{{ asset('css/richtext.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/image-uploader.min.css') }}">
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<link rel="stylesheet" href="{{ asset('css/jquery.datetimepicker.css') }}">

<link rel="stylesheet" href="{{ asset('css/estilo.css') }}">

    
    {% endblock %}


{% block myjavascripts %}
  
<script src="{{ asset('js/jquery-3.7.1.js') }}"></script>
<script src="{{ asset('js/jquery-ui.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('js/jquery.richtext.min.js') }}"></script>
<script src="{{ asset('js/image-uploader.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>    
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="https://kit.fontawesome.com/91464fdedc.js" crossorigin="anonymous"></script>


{# <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script> #}
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<script src="{{ asset('js/crearRuta.js') }}"></script>
<script src="{{ asset('js/añadirRuta.js') }}"></script>
<script src="{{ asset('js/extraerVisitas.js') }}"></script>
<script src="{{ asset('js/añadirVisita.js') }}"></script>

<script src="{{ asset('js/añadirProgr.js') }}"></script>
{# <script src="{{ asset('js/generarTour.js') }}"></script> #}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock %}


{% block main %}
<body>
    {# <div id="modal"> #}
        <div id="main">
{#####_________________________________________PESTAÑA CREAR/RUTA_____________________________######}
                <div id="tabs">
                    <ul>
                    <li><a href="#tabs-1">Ruta</a></li>
                    <li><a href="#tabs-2">Visitas</a></li>
                    <li><a href="#tabs-3">Programación</a> </li>
                    </ul>
                    <div id="tabs-1">
                    <div class="primerLinea">
                      <div>
                        <label for="titulo">Titulo:</label>
                        <input type="text" name="titulo" id="inputTitulo" required>
                      </div>
                      <div>
                        <label for="fechaRuta">Fecha inicio y fin </label> 
                        <input type="text" id="daterange" name="daterange" required value="" /> 
                        </div>
                        <div>
                        <label for="aforo" required >Aforo:</label>
                        <input type="number" min="6" max="20" id="aforo"> 
                        </div>
                        </div>
                         <br>
                      
                        <div class="primerLinea">
                        <div>
                          <label for="puntoEncuentro" class="subt">Punto de encuentro:</label>
                        <button id="btnMapa">Mapa</button>
                        </div>
                        <div>
                        <label for="x" required>EjeX:</label>
                        <input type="number" name="x" id="x">
                        </div>
                        <div>
                        <label for="y" required>EjeY:</label>
                        <input type="number" name="y" id="y">
                      </div>
                      </div>
                      <br>
                        <div id="modal"></div>
                        <label for="descripcion" class="subt">Descripción:</label>
                        <textarea name="descripcion" id="textarea" cols="1" rows="1"></textarea>
                        <label for="subirImagen" class="subt">Subir Imagen:</label>
                          <form action="url" enctype="multipart/form-data" id="foto">
                        <div id="input-images" class"input-images"></div>
                        </form>
                      
                        
                        <br>
                           <button class="btn btn-primary" type="button" id="btnRuta" >CREAR RUTA</button>
                    </div>
{#####_________________________________________PESTAÑA VISITAS____________________________________________________######}

                <div id="tabs-2">
                  <label for="">Selecciona una localidad</label>
                  <select name="" id="salutation" class="salutation">
                    <option disabled selected>Click en una</option>
                    {% for localidad in localidades %}
                      <option value="{{ localidad.id }}">{{ localidad.nombre }}</option>
                    {% endfor %}
                  </select>
                  <br>
                  <div class="titulosVisitas">
                    <label for="">Lugares disponibles</label>
                    <label for="">Lugares elegidos</label>
                  </div>
                  <div id="items" class="items">
                    <ul id="sortable1" class="droptrue">
                      {% for visita in visitas %}
                        <li class="visita" data-localidad="{{ visita.cod_localidad}}" data-visita-id="{{ visita.id }}">
                          <div class="image-container">
                            <img src="{{ asset('public/img/visitas/' ~ visita.foto) }}" alt="{{ visita.nombre }}">
                            <p class="text-center">{{ visita.nombre }}</p>
                          </div>
                        </li>
                      {% endfor %}
                    </ul>
                    <ul id="sortable2" class="droptrue">
                      
                    </ul>
                  </div>
                  <br>
                    <button class="btn btn-primary" type="button" Id="btnCrearVisitasTour">CREAR VISITAS</button>
                </div>

{#_____________________________________________PESTAÑA PROGRAMACION__________________________________________________#}
                    <div id="tabs-3">
                        <div class="fechaPeriodo">
                        <label for="periodo">Periodo</label> 
                       <input type="text" name="datefilter" value="" />
                          </div>
                          <div id="diasSemana">
                            <div>
                              <input type="checkbox" id="lunes" name="dia" value="L">
                              <label for="lunes">Lunes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="martes" name="dia" value="M">
                              <label for="martes">Martes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="miercoles" name="dia" value="X">
                            <label for="miercoles">Miércoles</label>
                            </div>
                            <div>
                              <input type="checkbox" id="jueves" name="dia" value="J">
                              <label for="jueves">Jueves</label>
                            </div>
                            <div>
                              <input type="checkbox" id="viernes" name="dia" value="V">
                              <label for="viernes">Viernes</label>
                            </div>
                            <div>
                              <input type="checkbox" id="sabado" name="dia" value="S">
                              <label for="sabado">Sábado</label>
                            </div>
                            <div>
                              <input type="checkbox" id="domingo" name="dia" value="D">
                              <label for="domingo">Domingo</label>
                            </div>
                          </div>
                          <div id="otrasOpcion">
                          <div>
                            <label for="salutation">Hora </label>
                            <input type="time" id="time" />
                          </div>           
                          <div>  
                          <form>
                          <label for="selectGuia">Selecciona un guía</label>
                           <select name="selectGuia" id="selectGuia">
                           <option disabled selected>....</option>
                             {% for guia in guias %}
                             <option value="{{guia.id}}" >{{ guia.nombre }}</option>
                             {% endfor %}
                            </select> 
                           </form>
                          </div> 
                         </div>
                        <br>
                        <div class="btnn">
                         <button class="bttnEstilo" id="guardar">Archivar</button>
                        </div>                 
                          <br>
                          <table id="tabla" border="1">
                            <thead>
                              <tr>
                                <th>Rango de fecha</th>
                                <th>Días</th>
                                <th>Hora</th>
                                <th>Guía</th>
                              </tr>
                            </thead>
                            <tbody>
                            </tbody>
                          </table>
                          <br>
                     <button class="btn btn-danger" type="button" id="btnCrearProgramacion">CREAR PROGRAMACION Y GENERAR TOUR</button>
                    </div>
                      
                </div>

{##________________________________________BOTONES CONTROLERS_______________________________________________________##}                
                <div class="d-grid gap-2">
                
                
                   
                    {# <button class="btn btn-danger" type="button" id="btnTour">GENERAR TOUR</button> #}
                  </div>         
        </div>
        
{# <div id="errorModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="errorMessage"></p>
    </div>
</div> #}
    {# </div> #}
</body>
{% endblock %}