src/Entity/Informe.php
<?php

namespace App\Entity;

use App\Repository\InformeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: InformeRepository::class)]
#[Broadcast]
class Informe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Tour $cod_tour = null;

    /**
 * @ORM\OneToOne(targetEntity=Tour::class, inversedBy="informe", cascade={"persist", "remove"})
 * @ORM\JoinColumn(name="cod_tour_id", referencedColumnName="id", onDelete="CASCADE")
 */


    #[ORM\Column(length: 255)]
    private ?string $imagen = null;

    #[ORM\Column(length: 255)]
    private ?string $observaciones = null;

    #[ORM\Column]
    private ?int $recaudacion = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodTour(): ?Tour
    {
        return $this->cod_tour;
    }

    public function setCodTour(?Tour $cod_tour): static
    {
        $this->cod_tour = $cod_tour;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): static
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getObservaciones(): ?string
    {
        return $this->observaciones;
    }

    public function setObservaciones(string $observaciones): static
    {
        $this->observaciones = $observaciones;

        return $this;
    }

    public function getRecaudacion(): ?int
    {
        return $this->recaudacion;
    }

    public function setRecaudacion(int $recaudacion): static
    {
        $this->recaudacion = $recaudacion;

        return $this;
    }
}

src/Entity/Tour.php
<?php

namespace App\Entity;

use App\Repository\TourRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: TourRepository::class)]
#[Broadcast]
class Tour
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_hora = null;

    #[ORM\ManyToOne(inversedBy: 'tours')]
    private ?Ruta $cod_ruta = null;

    #[ORM\OneToMany(mappedBy: 'cod_tour', targetEntity: UserTour::class, cascade: ['persist', 'remove'])]
    private Collection $userTours;

    #[ORM\OneToOne(mappedBy: 'cod_tour', targetEntity:Informe::class, cascade: ['persist', 'remove'])]
    private ?Informe $informe = null;

    #[ORM\Column(length: 255)]
    private ?string $id_guide = null;

    public function __construct()
    {
        $this->userTours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaHora(): ?\DateTimeInterface
    {
        return $this->fecha_hora;
    }

    public function setFechaHora(\DateTimeInterface $fecha_hora): static
    {
        $this->fecha_hora = $fecha_hora;

        return $this;
    }

    public function getCodRuta(): ?Ruta
    {
        return $this->cod_ruta;
    }

    public function setCodRuta(?Ruta $cod_ruta): static
    {
        $this->cod_ruta = $cod_ruta;

        return $this;
    }

    /**
     * @return Collection<int, UserTour>
     */
    public function getUserTours(): Collection
    {
        return $this->userTours;
    }

    public function addUserTour(UserTour $userTour): static
    {
        if (!$this->userTours->contains($userTour)) {
            $this->userTours->add($userTour);
            $userTour->setCodTour($this);
        }

        return $this;
    }

    public function removeUserTour(UserTour $userTour): static
    {
        if ($this->userTours->removeElement($userTour)) {
            // set the owning side to null (unless already changed)
            if ($userTour->getCodTour() === $this) {
                $userTour->setCodTour(null);
            }
        }

        return $this;
    }

    public function getIdGuide(): ?string
    {
        return $this->id_guide;
    }

    public function setIdGuide(string $id_guide): static
    {
        $this->id_guide = $id_guide;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre;
    }

}

src/Entity/UserTour.php
<?php

namespace App\Entity;

use App\Repository\UserTourRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity(repositoryClass: UserTourRepository::class)]
#[Broadcast]
class UserTour
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'userTours')]
    private ?User $cod_user = null;

    #[ORM\ManyToOne(inversedBy: 'userTours')]
    private ?Tour $cod_tour = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_reserva = null;
    
    #[ORM\OneToOne(mappedBy: 'cod_reserva', targetEntity: Valoracion::class, cascade: ['persist', 'remove'])]
    private ?Valoracion $valoracion = null;

    #[ORM\Column]
    private ?int $asistentes = null;

    #[ORM\Column]
    private ?int $num_gente_reserva = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodUser(): ?User
    {
        return $this->cod_user;
    }

    public function setCodUser(?User $cod_user): static
    {
        $this->cod_user = $cod_user;

        return $this;
    }

    public function getCodTour(): ?Tour
    {
        return $this->cod_tour;
    }

    public function setCodTour(?Tour $cod_tour): static
    {
        $this->cod_tour = $cod_tour;

        return $this;
    }

    public function getFechaReserva(): ?\DateTimeInterface
    {
        return $this->fecha_reserva;
    }

    public function setFechaReserva(\DateTimeInterface $fecha_reserva): static
    {
        $this->fecha_reserva = $fecha_reserva;

        return $this;
    }

    public function getAsistentes(): ?int
    {
        return $this->asistentes;
    }

    public function setAsistentes(int $asistentes): static
    {
        $this->asistentes = $asistentes;

        return $this;
    }

    public function getNumGenteReserva(): ?int
    {
        return $this->num_gente_reserva;
    }

    public function setNumGenteReserva(int $num_gente_reserva): static
    {
        $this->num_gente_reserva = $num_gente_reserva;

        return $this;
    }
}

src/Entity/Valoracion.php
<?php

namespace App\Entity;

use App\Repository\ValoracionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: ValoracionRepository::class)]
#[Broadcast]
class Valoracion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?UserTour $cod_reserva = null;

    #[ORM\Column]
    private ?int $nota_guia = null;

    #[ORM\Column]
    private ?int $nota_ruta = null;

    #[ORM\Column(length: 255)]
    private ?string $comentario = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodReserva(): ?UserTour
    {
        return $this->cod_reserva;
    }

    public function setCodReserva(?UserTour $cod_reserva): static
    {
        $this->cod_reserva = $cod_reserva;

        return $this;
    }

    public function getNotaGuia(): ?int
    {
        return $this->nota_guia;
    }

    public function setNotaGuia(int $nota_guia): static
    {
        $this->nota_guia = $nota_guia;

        return $this;
    }

    public function getNotaRuta(): ?int
    {
        return $this->nota_ruta;
    }

    public function setNotaRuta(int $nota_ruta): static
    {
        $this->nota_ruta = $nota_ruta;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->comentario;
    }

    public function setComentario(string $comentario): static
    {
        $this->comentario = $comentario;

        return $this;
    }
}

src/Controller/ClienteController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
USE App\Entity\Ruta;
use App\Entity\Tour;
use App\Entity\User;
use App\Entity\UserTour;
use App\Entity\Valoracion;
use App\Repository\ValoracionRepository;
use App\Repository\UserTourRepository;
use Symfony\Component\Security\Core\Security;
use App\Form\ReservarFormTour;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
USE App\Controller\Api\DevueltaRoute;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\User\UserInterface;
USE Symfony\Component\HttpFoundation\JsonResponse;
use App\Service\MessageGenerator;


class ClienteController extends AbstractController
{

    private DevueltaRoute $devueltaRoute;
    private SerializerInterface $serializer;
    private EntityManagerInterface $entityManager;
    public function __construct(DevueltaRoute $devueltaRoute, SerializerInterface $serializer, EntityManagerInterface $entityManager)
    {
        $this->devueltaRoute = $devueltaRoute;
        $this->serializer = $serializer;
        $this->entityManager = $entityManager;
    }
    

    #[Route('/cliente', name: 'app_cliente')]
    public function index(): Response
    {
        return $this->render('cliente/index.html.twig', [
            'controller_name' => 'ClienteController',
        ]);
    }




    #[Route('/verRutas', name: 'verRutas')]
    public function verRutas(): Response
    {
        //obtener la respuesta
        $response = $this->devueltaRoute->uploadCreateRoute(new Request(), $this->entityManager);

        // Decodificar el contenido JSON
        $rutas = json_decode($response->getContent(), true);

        return $this->render('cliente/rutas.html.twig', [
            'rutas' => $rutas,
        ]);
    }



    #[Route('/ruta/{id}/tours', name: 'ruta_tours')]
    public function showTours($id): Response
    {
      $ruta = $this->getDoctrine()->getRepository(Ruta::class)->find($id);

     if (!$ruta) {
        throw $this->createNotFoundException('No se encontró la ruta con id '.$id);
      }

      $tours = $ruta->getTours();

     return $this->render('cliente/tours.html.twig', [
          'tours' => $tours,
       ]);
    }



  #[Route('/reservar/{tourId}', name: 'reservar_tour')]
    public function reservar(Request $request, $tourId, UserInterface $user, MessageGenerator $messageGenerator): Response 
    {
        // Obtener el tour según el ID proporcionado
        $tour = $this->entityManager->getRepository(Tour::class)->find($tourId);

        if (!$tour) {
            throw $this->createNotFoundException('Tour no encontrado');
        }

        $visitas = [];
        foreach ($tour->getCodRuta()->getRutaVisitas() as $rutaVisita) {
            $visitas[] = $rutaVisita->getCodVisita();
        }
      

      
        $userTour = new UserTour();
        $userTour->setCodUser($user);
        $userTour->setFechaReserva(new \DateTime());
      
        $form = $this->createForm(ReservarFormTour::class, $userTour);
        $form->get('num_gente_reserva')->setData('0');
      
        $form->handleRequest($request);

        // Si el formulario se envía y es válido
        if ($form->isSubmitted() && $form->isValid()) {
            $userTour->setCodTour($tour);
            $this->entityManager->persist($userTour);
            $this->entityManager->flush();

            $nombreUsuario = $userTour->getCodUser()->getNombre(); // Reemplaza 'nombreUsuario' con el nombre real del campo en tu entidad UserTour
            $fechaReserva = $userTour->getFechaReserva()->format('Y-m-d H:i:s');
            $Asistentes = $userTour->getAsistentes();
            // Agrega más campos según tu estructura de formulario y entidad
    
            $cuerpoCorreo = "Gracias por reservar el tour. Detalles de la reserva:\n";
            $cuerpoCorreo .= "Nombre del usuario: $nombreUsuario\n";
            $cuerpoCorreo .= "Fecha de reserva: $fechaReserva\n";
            $cuerpoCorreo .= "Asistentes: $Asistentes\n";
            // Agrega más líneas según la información que desees incluir
    
            // Llama al método sendMail del servicio MessageGenerator
            $correo = $user->getEmail();  // O la dirección de correo relevante
            $messageGenerator->sendMail($correo, $cuerpoCorreo);

            return $this->redirectToRoute('verReservas');
        }

       
        return $this->render('cliente/tours.html.twig', [
            'form' => $form->createView(),
            'tour' => $tour, 
            'ruta' => $tour->getCodRuta(),
            'visitas' => $visitas, 
        ]);
    }


  
    #[Route('/misReservas', name: 'verReservas')]
  public function verReservas(UserTourRepository $userTourRepository, ValoracionRepository $valoracionRepository, UserInterface $user): Response
  {
      // Obtener el ID 
      $userId = $user->getId();
  
      // Verificar 
      if ($userId) {
          // Obtener las reservas del usuario
          $reservasUsuario = $userTourRepository->findBy(['cod_user' => $userId]);

          return $this->render('cliente/reservas.html.twig', [
              'reservasUsuario' => $reservasUsuario,
               
          ]);
      }
  
      return $this->redirectToRoute('app_home');
  }



     #[Route('/procesar-valoracion', name: 'ruta_para_procesar_valoracion')]
    public function procesarValoracion(Request $request, EntityManagerInterface $entityManager, ValoracionRepository $valoracionRepository): Response
    {
         //  ID de la reserva desde el formulario
         $idReserva = $request->request->get('cod_reserva');
        //  ID proporcionado
        $reserva = $this->entityManager->getRepository(UserTour::class)->find($idReserva);
    
        if (!$reserva) {
            throw $this->createNotFoundException('Reserva no encontrada');
        }
    
        $valoracionExistente = $valoracionRepository->findOneBy(['cod_reserva' => $reserva]);

        if ($valoracionExistente) {
            $this->addFlash('error', 'Ya has valorado esta reserva');
            // return new JsonResponse(['error' => 'Ya has valorado esta reserva']);
            return $this->redirectToRoute('app_cliente_valoracion');
           
        }
    
    
        $valoracion = new Valoracion();
        $valoracion->setCodReserva($reserva);
        $valoracion->setNotaGuia($request->request->get('nota_guia'));
        $valoracion->setNotaRuta($request->request->get('nota_ruta'));
        $valoracion->setComentario($request->request->get('comentario'));
    
   
        $entityManager->persist($valoracion);
        $entityManager->flush();
    
       
        $this->addFlash('success', '¡La valoración se ha guardado con éxito!');
    
       
        return $this->redirectToRoute('app_cliente_valoracion');
    }



    #[Route('/verValoraciones', name: 'verValoraciones')]
     public function verValoraciones(UserTourRepository $userTourRepository, ValoracionRepository $valoracionRepository, UserInterface $user): Response
    {
     
        $userId = $user->getId();
    
        if ($userId) {
            $reservasUsuario = $userTourRepository->findBy(['cod_user' => $userId]);
            $valoracionesUsuario = $valoracionRepository->findBy(['cod_reserva' => $reservasUsuario]);
            return $this->render('cliente/valoracion.html.twig', [
                'reservasUsuario' => $reservasUsuario,
                'valoracionesUsuario' => $valoracionesUsuario,
            ]);
        }
    
        //  caso en el que el usuario no está autenticado
        return $this->redirectToRoute('app_home');
    }
    

// #[Route('/verRutas', name: 'verRutas')]
    // public function verRutas(): Response
    // {
    //     $response = $this->forward(DevueltaRoute::class.'::uploadCreateRoute');
    //     $rutas = json_decode($response->getContent(), true);
    // // var_dump($rutas);
    //     return $this->render('cliente/rutas.html.twig', [
    //         'rutas' => $rutas,
    //     ]);
    // }






        }

templates/cliente/cuerpo.html.twig
{#.............CUERPO....................................................................................................................#}

  {# <div class="text-center bg-image imageHeader">
  <div class="mask">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white mb-2">
        <h5 class="mt-3 mb-4">¡BIENVENIDO! ENCUENTRA TU PRÓXIMO TOUR</h5>
        <div class="btn btn-outline-light">
          <div data-mdb-ripple-init class="btn btn-lg m-2">
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="¿Málaga, Barcelona ó ....?" aria-label="Search">
            </form>
          </div>
          <p data-mdb-ripple-init class="btn btn-lg m-2">
            <input class="form-control me-2" type="text" placeholder="dd/mm/aa" id="datepicker">
          </p>
          <button class="btn btn-outline-success m-2" type="submit">Buscar</button>
        </div>
      </div>
    </div>
  </div>
</div> #}

{#..........................CARRUSEL CONBINADO CON TARJETAS.................................................................................#}

<div class="row row-cols-1 row-cols-md-3 g-4 mt-1 mb-2" style="margin-left: 2px; margin-right:2px">
    <div class="col">
    <div class="card h-100">
    <img src="{{ asset('img/barcelona.jpg') }}"class="card-img-top" alt="...">
      <div class="card-body">
         <h5 class="card-title">Barcelona</h5>
        <p class="card-text"> Su historia rica y su arquitectura modernista y Art Nouveau la convierten en un centro cultural vibrante. Famosa por su individualidad, interés cultural y belleza física.</p>
      </div>
    
    </div>
  </div>
{#...........................................................................................................#}
  <div class="col">
  <div class="card h-100">
   <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <!-- Indicadores -->
        {# <ol class="carousel-indicators">
            <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
        </ol> #}
        <!-- Slides -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ asset('img/madridddd.jpg') }}" class="d-block w-100" alt="Jaén">
                <div class="carousel-caption">
                    <h5>Madrid</h5>
                    
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{ asset('img/cordobaaaa.jpg') }}" class="d-block w-100" alt="Córdoba">
              <div class="carousel-caption">
                    <h5>Cordoba</h5>
                    
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{ asset('img/granada.jpg') }}" class="d-block w-100" alt="Granada">
                <div class="carousel-caption">
                    <h5>Granada</h5>
                   
                </div>
            </div>
           
        </div>
         <div class="card-body">
         <h5 class="card-title text-center text-capitalize tendencia">Destinos favoritos</h5>
          {# <p class="card-text text-center text-info"> Las ciudades mas visitadas en esta época del año....</p> #}
          <img src="{{ asset('img/calificacion.png') }}" class="d-block w-100" >
       </div>
        
        <!-- Controles -->
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Siguiente</span>
        </a>
    </div>
  </div>
  </div>
  {#........................................................................................................#}
  <div class="col">
    <div class="card h-100">
    <img src="{{ asset('img/jaenmejorciudad.jpg') }}"class="card-img-top" alt="...">
      <div class="card-body">
         <h5 class="card-title">jaen</h5>
        <p class="card-text">Entre sus atractivos destacan la Catedral, joya arquitectónica del Renacimiento español, además de ser "Capital Mundial del Aceite de Oliva".</p>
      </div>
    
    </div>
  </div>
{#..............................................................................................................#}
</div>

templates/cliente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cliente{% endblock %}


{% block body %}


{% include 'cliente/nav.html.twig' %}


{% endblock %}

{% block main %}

{% include 'cliente/cuerpo.html.twig' %}

{% endblock %}

templates/cliente/nav.html.twig
{% if is_granted('IS_AUTHENTICATED_FULLY') %}

<div class="hstack gap-3">
    <!-- Logo y título -->
    <div class="p-2">
        <a class="nav-link" href="{{ path('app_cliente') }}">
            <img src="{{ asset('img/logo.png') }}" alt="Logo" width="100" class="d-inline-block align-text-top">
        </a>
        
    </div>
    <div class="p-2">
        <h2 class="link-dangerous">FREE TOURS POR ESPAÑA</h2>
    </div>

    <!-- Opciones -->
    <div class="p-2">
        <a class="nav-link" id="ruta-link" href="{{ path('app_cliente_ver_rutas') }}">Rutas</a>
    </div>
    <div class="p-2">
        <a class="nav-link" id="reservas-link"  href="{{ path('app_cliente_ver_reservas') }}">Reservas</a>
    </div>
    <div class="p-2">
        <a class="nav-link" id="otraOpcion-link" href="{{path('app_cliente_valoracion') }}">Valoraciones</a>
    </div>

    <!-- Botón de cerrar sesión -->
  <div class="p-2 dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
        {{ app.user.email }}
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {# <li><a class="dropdown-item" href="#">Ajustes</a></li>
        <li><a class="dropdown-item" href="#">Correo</a></li> #}
        <li><a class="dropdown-item" href="{{ path('app_logout') }}">Cerrar Sesión</a></li>
    </ul>
</div>
</div>
  {% endif %}

templates/cliente/reservaEmail.html.twig
<h3>¡Reserva confirmada!</h3>

<p>Hola {{ user.username }},</p>
<p>Tu reserva para el tour {{ tour.nombre }} en la ruta {{ ruta.nombre }} se ha confirmado con éxito.</p>
<p>Detalles de la reserva:</p>
<ul>
    <li>Fecha de reserva: {{ userTour.fechaReserva|date('Y-m-d H:i:s') }}</li>
    <li>Número de asistentes: {{ userTour.asistentes }}</li>
    <!-- Agrega más detalles según sea necesario -->
</ul>

templates/cliente/valoracion.html.twig
{% extends 'cliente/index.html.twig' %}

{% block title %}Mis Valoraciones | {{ parent() }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
  <style>
.card:hover {
    transform: scale(1.04);
    transition: transform .2s;
}
</style>
{% endblock %}


{% block body %}
      
    <script>
        {% for flashMessage in app.flashes('error') %}
          
            alert("{{ flashMessage }}");
           
        {% endfor %}

        {% for flashMessage in app.flashes('success') %}
          
            alert("{{ flashMessage }}");
        
        {% endfor %}
    </script>
    


{% if is_granted('IS_AUTHENTICATED_FULLY') %}

<div class="hstack gap-3">
    <!-- Logo y título -->
    <div class="p-2">
        <a class="nav-link" href="{{ path('app_cliente') }}">
            <img src="{{ asset('img/logo.png') }}" alt="Logo" width="100" class="d-inline-block align-text-top">
        </a>
        
    </div>
    <div class="p-2">
        <h2 class="link-dangerous">FREE TOURS POR ESPAÑA</h2>
    </div>

    <!-- Opciones -->
    <div class="p-2">
       <a class="nav-link" id="ruta-link" href="{{ path('app_cliente_ver_rutas') }}">Rutas</a>
    </div>
    <div class="p-2">
        <a class="nav-link" id="reservas-link"  href="{{ path('app_cliente_ver_reservas') }}">Reservas</a>
    </div>
    <div class="p-2 d-inline-flex focus-ring py-1 px-2 text-decoration-none border rounded-2">
        <a class="nav-link link-success" id="otraOpcion-link" href="{{path('app_cliente_valoracion') }}">Valoraciones</a>
    </div>

    <!-- Botón de cerrar sesión -->
  <div class="p-2 dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
        {{ app.user.email }}
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li><a class="dropdown-item" href="{{ path('app_logout') }}">Cerrar Sesión</a></li>
    </ul>
</div>
</div>
  {% endif %}



{% endblock %}

{% block main %}
  <div class="container mt-2">
    <h3 class="mb-4 display-1 text-success text-decoration-underline text-uppercase text-center">Historial de valoraciones</h3>
    {% if valoracionesUsuario is not empty %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for valoracion in valoracionesUsuario %}
                <div class="col">
                    <div class="card h-100 shadow-sm rounded mb-3 bg-success text-white">
                        <div class="card-body">
                            {# <h5 class="card-title">Fecha de la Valoración: {{ valoracion.createdAt|date('Y-m-d H:i:s') }}</h5> #}
                            <p class="card-text">Nota Guía: {{ valoracion.notaGuia }}</p>
                            <p class="card-text">Nota Ruta: {{ valoracion.notaRuta }}</p>
                            <p class="card-text">Comentario: {{ valoracion.comentario }}</p>
                        </div>
                        <!-- Detalles de la Reserva -->
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-light text-dark"><strong>Nombre del Tour:</strong> {{ valoracion.codReserva.codTour.codRuta.nombre }}</li>
                            <li class="list-group-item bg-light text-dark"><strong>Fecha y Hora del Tour:</strong> {{ valoracion.codReserva.codTour.fechaHora|date('Y-m-d H:i:s') }}</li>
                            <li class="list-group-item bg-light text-dark"><strong>Id Guía Asignado:</strong> {{ valoracion.codReserva.codTour.idGuide }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="mt-4">No tienes valoraciones actualmente.</p>
    {% endif %}
</div>
{% endblock %}